<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE irProfiles PUBLIC "-//homecinema-fr//IRProfiles XML//EN" [
   <!ELEMENT irProfiles (profile+)>
   <!ATTLIST irProfiles version CDATA #REQUIRED>
   
   <!ELEMENT irProfile (description, author, code+, delay+)>
   <!ATTLIST irProfile name CDATA #REQUIRED>
   
   <!ELEMENT description (#PCDATA)>
   <!ELEMENT author (#PCDATA)>
   <!ELEMENT code (#PCDATA)>
   <!ATTLIST code function (rightArrow | leftArrow | downArrow | upArrow | nextChapter | ok) #REQUIRED>
   <!ELEMENT delay (#PCDATA)>
   <!ATTLIST code function (menuNavigation | menuValidation | chapterNavigation) #REQUIRED>
]>
<irProfiles version="1">
  <irProfile name="Denon">
    <description></description>
    <author>homecinema-fr.com</author>
    <code function='ok'>0000 006D 0020 0000 000C 001C 000C 001B 000C 001C 000C 0043 000C 001C 000C 0043 000C 0042 000C 001C 000C 0043 000C 0042 000C 0043 000C 001C 000C 0042 000C 001C 000C 001C 000C 066B 000C 001C 000C 001B 000C 001C 000C 0043 000C 001C 000C 001C 000C 001B 000C 0043 000C 001C 000C 001C 000C 001B 000C 0043 000C 001C 000D 0042 000C 0042 000C 06B8</code>
    <code function='rightArrow'>0000 006D 0020 0000 000C 001B 000C 001C 000C 001C 000C 0043 000C 001C 000C 001B 000C 0043 000C 0042 000C 0043 000C 001C 000C 0043 000C 001B 000C 0043 000C 001C 000C 001C 000C 0691 000C 001C 000C 001C 000C 001C 000C 0043 000B 001D 000C 0042 000C 001C 000C 001C 000C 001C 000C 0042 000C 001C 000C 0042 000C 001D 000B 0043 000C 0043 000C 0691</code>
    <code function='downArrow'>0000 006D 0020 0000 000C 001C 000C 001B 000C 001C 000C 0043 000C 001C 000C 0043 000C 001B 000C 0043 000C 0043 000C 001B 000C 0043 000C 001C 000C 0043 000C 001B 000C 001C 000C 0692 000C 001C 000C 001B 000C 001C 000C 0043 000C 001C 000C 001C 000C 0042 000C 001C 000C 001C 000C 0043 000B 001C 000C 0043 000C 001C 000C 0042 000C 0043 000C 0691</code>
    <code function='nextChapter'>0000 006D 0020 0000 000C 001C 000C 001B 000C 001C 000C 0043 000C 001C 000C 001C 000C 001B 000C 001C 000C 0043 000C 0043 000B 001C 000C 001C 000C 0043 000C 001C 000C 001C 000C 06DF 000C 001B 000C 001C 000C 001C 000C 0043 000C 001C 000C 0042 000C 0043 000C 0043 000B 001D 000C 001B 000C 0043 000C 0042 000C 001C 000C 0043 000C 0043 000C 0643</code>
    <delay function='menuNavigation'>300</delay>
    <delay function='menuValidation'>2000</delay>
    <delay function='chapterNavigation'>1500</delay>
  </irProfile>
  <irProfile name="Marantz">
    <description></description>
    <author>homecinema-fr.com</author>
    <code function='ok'>6000 0000 0000 0001 0004 005C</code>
    <code function='rightArrow'>6000 0000 0000 0001 0004 005B</code>
    <code function='downArrow'>6000 0000 0000 0001 0004 0059</code>
    <code function='nextChapter'>6000 0000 0000 0001 0004 0020</code>
	<delay function='menuNavigation'>300</delay>
	<delay function='menuValidation'>2000</delay>
	<delay function='chapterNavigation'>1500</delay>
  </irProfile>
  <irProfile name="Onkyo">
    <description>Attention, profile incomplet</description>
    <author>homecinema-fr.com</author>
    <code function='ok'></code>
    <code function='rightArrow'></code>
    <code function='downArrow'></code>
    <code function='nextChapter'>0000 006d 0022 0002 0154 00ab 0015 0015 0015 0040 0015 0015 0015 0015 0015 0040 0015 0015 0015 0040 0015 0040 0015 0040 0015 0040 0015 0015 0015 0040 0015 0015 0015 0040 0015 0015 0015 0015 0015 0040 0015 0015 0015 0040 0015 0040 0015 0040 0015 0015 0015 0015 0015 0015 0015 0015 0015 0040 0015 0015 0015 0015 0015 0015 0015 0040 0015 0040 0015 0040 0015 05ea 0154 0054 0015 0e33</code>
	<delay function='menuNavigation'>300</delay>
	<delay function='menuValidation'>2000</delay>
	<delay function='chapterNavigation'>1500</delay>
  </irProfile>
  <irProfile name="Oppo">
    <description></description>
    <author>homecinema-fr.com</author>
    <code function='ok'>0000 006D 0024 0000 0154 00A8 0016 003E 0017 0014 0016 0014 0016 003F 0016 0014 0018 0012 0017 003E 0016 0014 0017 0015 0015 003E 0017 003D 0017 0014 0017 003D 0017 003E 0017 0013 0017 003E 0016 003F 0017 003D 0018 0013 0017 0013 0016 003F 0016 0014 0016 003F 0016 0014 0016 0014 0017 0014 0016 003E 0017 003E 0016 0014 0017 003E 0016 0014 0017 003E 0016 05DD 0154 0053 0017 08FF</code>
    <code function='rightArrow'>0000 006D 0024 0000 0155 00A7 0017 003E 0017 0013 0017 0014 0017 003D 0017 0014 0017 0013 0016 003F 0016 0014 0016 0014 0017 003E 0016 003E 0017 0014 0016 003E 0017 003E 0017 0013 0017 003E 0017 003E 0016 003E 0017 003E 0017 003E 0016 0014 0017 0013 0017 003E 0017 0013 0017 0014 0016 0014 0016 0014 0017 0014 0016 003E 0017 003E 0016 0014 0017 003D 0017 05DD 0155 0052 0017 08FF</code>
    <code function='downArrow'>0000 006D 0024 0000 0153 00A8 0016 0040 0016 0014 0015 0015 0016 003E 0016 0015 0016 0014 0017 003E 0016 0014 0016 0014 0016 003F 0015 0040 0016 0014 0017 003E 0016 003F 0016 0014 0016 003E 0016 0015 0015 0015 0017 0014 0015 0015 0016 003E 0017 0013 0016 0015 0016 0015 0015 003F 0016 003E 0016 0040 0015 003F 0016 0015 0015 003F 0016 003E 0016 003F 0016 05DD 0153 0054 0016 08FF</code>
    <code function='nextChapter'>0000 006D 0024 0000 0151 00AB 0014 0041 0013 0016 0016 0016 0014 0041 0013 0016 0013 0017 0014 0042 0013 0016 0014 0017 0013 0041 0014 0041 0014 0017 0014 003F 0016 003F 0014 0017 0014 0041 0014 0016 0014 0016 0015 0016 0013 0016 0014 0042 0014 0016 0014 0040 0014 0016 0014 0041 0014 0041 0014 0041 0014 0041 0014 0016 0014 0040 0014 0016 0014 0041 0014 05DF 0152 0056 0014 08FF</code>
	<delay function='menuNavigation'>300</delay>
	<delay function='menuValidation'>2000</delay>
	<delay function='chapterNavigation'>1500</delay>
  </irProfile>
  <irProfile name="Philips">
    <description></description>
    <author>homecinema-fr.com</author>
    <code function='ok'>6000 0000 0000 0001 0004 005C</code>
    <code function='rightArrow'>6000 0000 0000 0001 0004 005B</code>
    <code function='downArrow'>6000 0000 0000 0001 0004 0059</code>
    <code function='nextChapter'>6000 0000 0000 0001 0004 0020</code>
	<delay function='menuNavigation'>300</delay>
	<delay function='menuValidation'>2000</delay>
	<delay function='chapterNavigation'>1500</delay>
  </irProfile>
  <irProfile name="Pioneer">
    <description></description>
    <author>homecinema-fr.com</author>
    <code function='ok'>0000 0067 0000 0044 0156 00ab 0016 003f 0016 0040 0015 0015 0016 0015 0016 0015 0015 0040 0016 0015 0015 0040 0016 0015 0015 0015 0016 0040 0015 0040 0016 003f 0016 0015 0016 003f 0016 0015 0016 003f 0016 0015 0016 0015 0015 0040 0016 003f 0016 0015 0016 0015 0015 0040 0016 0015 0015 0040 0016 003f 0016 0015 0016 0015 0015 0040 0016 003f 0016 0015 0016 03fe 0156 00ab 0016 003f 0016 0040 0015 0040 0016 003f 0016 0015 0016 003f 0016 0015 0016 003f 0016 0015 0016 0015 0015 0015 0016 0015 0016 003f 0016 0015 0016 003f 0016 0015 0016 003f 0016 0040 0015 0040 0016 003f 0016 0015 0016 003f 0016 0040 0015 0040 0016 0015 0015 0015 0016 0015 0016 0015 0015 0040 0016 0015 0015 0015 0016 0015 0016 03fe</code>
    <code function='rightArrow'>0000 0067 0000 0044 0156 00ab 0016 003f 0016 0040 0015 0015 0016 0015 0016 0015 0015 0040 0016 0015 0015 0040 0016 0015 0015 0015 0016 0040 0015 0040 0016 003f 0016 0015 0016 003f 0016 0015 0016 003f 0016 0015 0016 0015 0015 0040 0016 003f 0016 0015 0016 0015 0015 0040 0016 0015 0015 0040 0016 003f 0016 0015 0016 0015 0015 0040 0016 003f 0016 0015 0016 03fe 0156 00ab 0016 003f 0016 0040 0015 0040 0016 003f 0016 0015 0016 003f 0016 0015 0016 003f 0016 0015 0016 0015 0015 0015 0016 0015 0016 003f 0016 0015 0016 003f 0016 0015 0016 0015 0015 0015 0016 0040 0015 0015 0016 0015 0016 003f 0016 0040 0015 0015 0016 0040 0015 0040 0016 0015 0015 0040 0016 003f 0016 0015 0016 0015 0015 0040 0016 03fe</code>
    <code function='downArrow'>0000 0067 0000 0044 0156 00ab 0016 003f 0016 0040 0015 0015 0016 0015 0016 0015 0015 0040 0016 0015 0015 0040 0016 0015 0015 0015 0016 0040 0015 0040 0016 003f 0016 0015 0016 003f 0016 0015 0016 003f 0016 0015 0016 0015 0015 0040 0016 003f 0016 0015 0016 0015 0015 0040 0016 0015 0015 0040 0016 003f 0016 0015 0016 0015 0015 0040 0016 003f 0016 0015 0016 03fe 0156 00ab 0016 003f 0016 0040 0015 0040 0016 003f 0016 0015 0016 003f 0016 0015 0016 003f 0016 0015 0016 0015 0015 0015 0016 0015 0016 003f 0016 0015 0016 003f 0016 0015 0016 003f 0016 0040 0015 0015 0016 0015 0016 003f 0016 0040 0015 0040 0016 003f 0016 0015 0016 0015 0015 0040 0016 003f 0016 0015 0016 0015 0015 0015 0016 0015 0016 03fe</code>
    <code function='nextChapter'>0000 0067 0000 0022 0156 00ab 0016 003f 0016 0040 0015 0015 0016 0015 0016 0015 0015 0040 0016 0015 0015 0040 0016 0015 0015 0015 0016 0040 0015 0040 0016 003f 0016 0015 0016 003f 0016 0015 0016 0015 0015 0015 0016 0040 0015 0040 0016 003f 0016 0015 0016 0015 0015 0040 0016 003f 0016 0040 0015 0015 0016 0015 0016 0015 0015 0040 0016 003f 0016 0015 0016 03fe</code>
	<delay function='menuNavigation'>300</delay>
	<delay function='menuValidation'>2000</delay>
	<delay function='chapterNavigation'>1500</delay>
  </irProfile>
  <irProfile name="Samsung BDP1000">
    <description></description>
    <author>homecinema-fr.com</author>
    <code function='ok'>0000 006D 0027 0000 00A9 00A6 0013 0013 0013 0012 0013 0012 0013 0012 0013 0012 0013 0037 0013 0012 0013 0012 0013 0013 0013 0011 0013 0013 0013 0012 0013 0012 0013 0012 0013 0013 0012 0012 0013 00A8 0013 0036 0013 0037 0013 0037 0013 0012 0013 0012 0013 0012 0013 0037 0013 0036 0013 0037 0013 0012 0013 0012 0013 0012 0014 0036 0013 0037 0013 0012 0013 0012 0013 0012 0013 0037 0013 0036 0013 0037 0013 08FF</code>
    <code function='rightArrow'>0000 006D 0038 0000 00A9 00A7 0013 0013 0012 0013 0013 0012 0013 0012 0013 0012 0013 0038 0012 0013 0013 0011 0013 0013 0012 0013 0012 0013 0013 0013 0012 0013 0012 0012 0013 0013 0012 0013 0012 00A9 0012 0037 0012 0038 0012 0039 0011 0014 0011 0013 0012 0038 0012 0013 000A 0003 0004 0039 0010 0039 0005 0002 000A 0015 0001 0001 0001 0002 000A 0016 000C 0002 0003 0014 0007 0003 0007 0038 0007 0001 0007 0017 000A 0002 0001 0001 0003 0039 0008 0004 0005 0014 0006 0002 0005 0001 0002 0015 0009 0004 0004 0038 0008 0004 0006 0037 0008 0002 0006 003A 0004 0002 0001 0001 0007 08FF</code>
    <code function='downArrow'>0000 006D 0028 0000 00A9 00A7 0013 0012 0013 0012 0013 0012 0013 0013 0012 0013 0012 0037 0013 0014 0012 0012 0012 0013 0013 0012 0013 0012 0013 0012 0013 0014 0001 0001 0010 0012 0012 0013 0013 0013 0012 00A7 0013 0037 0013 0037 0012 0037 0013 0012 0013 0037 0013 0012 0013 0012 0014 0036 0013 0037 0012 0013 0013 0012 0013 0012 0013 0012 0013 0037 0013 0037 0013 0012 0013 0012 0012 0037 0013 0037 0013 0038 0013 08FF</code>
    <code function='nextChapter'>0000 006D 0027 0000 00AA 00A6 0014 0012 0013 0012 0013 0012 0013 0012 0013 0012 0013 0037 0013 0012 0013 0012 0013 0013 0013 0012 0013 0012 0013 0012 0013 0012 0013 0012 0013 0013 0013 0011 0014 00A7 0013 0036 0014 0036 0014 0036 0013 0012 0013 0037 0013 0012 0013 0012 0014 0011 0014 0036 0014 0011 0015 0010 0014 0011 0014 0011 0014 0036 0014 0035 0014 0036 0014 0011 0014 0036 0014 0035 0014 0036 0014 08FF</code>
	<delay function='menuNavigation'>500</delay>
	<delay function='menuValidation'>3000</delay>
	<delay function='chapterNavigation'>3000</delay>
  </irProfile>
  <irProfile name="Toshiba SD 350">
    <description></description>
    <author>homecinema-fr.com</author>
    <code function='ok'>0000 006D 0024 0000 0152 00A6 0017 003D 0016 0014 0017 003D 0017 0013 0017 0013 0017 0013 0017 003D 0018 0012 0017 0014 0016 003D 0017 0013 0017 003D 0017 003E 0017 003C 0017 0013 0017 003D 0017 003D 0017 0013 0017 0013 0017 0014 0017 0013 0017 003C 0017 0014 0017 0012 0018 0012 0017 003E 0017 003D 0017 003C 0017 003E 0017 0013 0017 003D 0017 003C 0017 05D9 0150 0053 0017 08FF</code>
    <code function='rightArrow'>0000 006D 0024 0000 0151 00A6 0017 003D 0017 0013 0017 003D 0017 0013 0017 0013 0017 0014 0017 003C 0017 0014 0017 0013 0017 003D 0017 0013 0017 003C 0017 003D 0017 003E 0017 0013 0017 003D 0016 003D 0017 0013 0017 003D 0017 003D 0017 0013 0017 0013 0017 003E 0017 0012 0017 0013 0017 003D 0018 0012 0017 0014 0017 003C 0017 003E 0017 0013 0017 003D 0017 05D9 0151 0053 0017 08FF</code>
    <code function='downArrow'>0000 006D 0024 0000 0152 00A5 0017 003D 0017 0013 0017 003E 0017 0012 0017 0013 0017 0014 0017 003C 0018 0013 0017 0013 0017 003D 0017 0013 0017 003D 0016 003E 0017 003D 0017 0013 0017 003D 0017 003C 0017 0014 0017 0013 0017 0013 0017 0013 0017 0014 0017 0012 0018 003C 0017 0013 0017 003E 0016 003D 0017 003D 0017 003D 0017 003D 0017 003D 0017 0013 0017 05D9 0152 0053 0016 08FF</code>
    <code function='nextChapter'>0000 006D 0024 0000 0151 00A7 0017 003D 0017 0013 0017 003C 0017 0014 0017 0013 0017 0013 0017 003D 0017 0013 0017 0014 0016 003D 0017 0013 0017 003D 0017 003D 0017 003D 0017 0014 0016 003D 0017 0013 0017 0013 0018 003C 0017 0013 0018 0012 0017 003E 0017 0013 0017 0012 0017 003E 0017 003C 0017 0014 0017 003C 0017 003D 0017 0013 0017 003E 0017 003C 0017 05DA 0151 0052 0017 08FF</code>
	<delay function='menuNavigation'>500</delay>
	<delay function='menuValidation'>3000</delay>
	<delay function='chapterNavigation'>3000</delay>
  </irProfile>
  <irProfile name="Toshiba XE1">
    <description></description>
    <author>homecinema-fr.com</author>
    <code function='ok'>0000 006D 0024 0000 014F 00AC 0014 003F 0014 0017 0014 0040 0013 0018 0013 0016 0014 0017 0014 0041 0013 0016 0013 0042 0013 0017 0013 0041 0015 0015 0015 003F 0014 0041 0013 0017 0014 003F 0014 0041 0014 0017 0014 0015 0015 0015 0014 0017 0014 0040 0014 0017 0015 0014 0015 0015 0015 003F 0015 0041 0014 003F 0015 003F 0014 0017 0014 0041 0013 0041 0014 05E5 014F 0055 0015 08FF</code>
    <code function='rightArrow'>0000 006D 0024 0000 0151 00AA 0016 003E 0017 0013 0016 003F 0015 0015 0015 0015 0015 0016 0015 003E 0016 0014 0016 003F 0015 0015 0016 003F 0015 0015 0015 003F 0016 003E 0016 0014 0016 003F 0015 003F 0015 0015 0016 003E 0016 003E 0016 0014 0016 0015 0015 003F 0016 0014 0016 0014 0017 003D 0016 0015 0015 0015 0016 003E 0016 003F 0015 0015 0015 003F 0016 05E3 0151 0054 0016 08FF</code>
    <code function='downArrow'>0000 006D 0024 0000 0152 00A9 0015 003F 0016 0015 0015 003F 0015 0015 0015 0015 0016 0014 0016 003E 0016 0015 0017 003D 0015 0015 0017 003D 0016 0015 0015 003F 0015 003F 0016 0014 0016 003E 0016 003F 0015 0015 0015 0015 0016 0014 0016 0014 0017 0014 0015 0015 0016 003E 0016 0014 0016 003E 0016 003F 0015 003F 0016 003E 0016 003E 0016 003F 0015 0015 0017 05E2 0151 0054 0016 08FF</code>
    <code function='nextChapter'>0000 006D 0024 0000 0152 00AA 0016 003D 0017 0014 0016 003F 0016 0014 0016 0014 0016 0013 0017 003F 0015 0015 0016 003D 0017 0013 0017 003E 0016 0015 0015 003E 0017 003E 0016 0014 0016 003F 0015 0015 0017 0013 0016 003E 0016 0014 0016 0015 0016 003D 0017 0014 0016 0014 0016 003F 0015 003E 0017 0013 0019 003C 0016 003E 0016 0015 0016 003D 0017 003D 0017 05E4 0151 0053 0016 08FF</code>
	<delay function='menuNavigation'>500</delay>
	<delay function='menuValidation'>2000</delay>
	<delay function='chapterNavigation'>5000</delay>
  </irProfile>
  <irProfile name="Yamaha S2500">
    <description></description>
    <author>homecinema-fr.com</author>
    <code function='ok'>6000 0000 0000 0001 0004 005C</code>
    <code function='rightArrow'>6000 0000 0000 0001 0004 005B</code>
    <code function='downArrow'>6000 0000 0000 0001 0004 0059</code>
    <code function='nextChapter'>6000 0000 0000 0001 0004 0020</code>
	<delay function='menuNavigation'>300</delay>
	<delay function='menuValidation'>2000</delay>
	<delay function='chapterNavigation'>1500</delay>
  </irProfile>
  <irProfile name="PS3_bluwave">
    <description>Codes IR pour une playStation 3 associée à un dongle USB_IR Bluwave</description>
    <author>noname/HCFR</author>
    <code function='ok'>0000 006D 0024 0000 0152 00AB 0017 0014 0017 0014 0017 0014 0017 0015 0017 0014 0017 0015 0016 0015 0017 0014 0016 0014 0017 0040 0017 003F 0017 0014 0018 003F 0017 003F 0017 003F 0017 0041 0016 0015 0016 0040 0016 0014 0017 0014 0018 003F 0017 0015 0017 003E 0018 0014 0017 003F 0017 0014 0017 0040 0017 003F 0017 0014 0017 0040 0017 0015 0016 0040 0016 062E 0151 0056 0016 08FF</code>
    <code function='rightArrow'>0000 006D 0024 0000 0153 00AB 0016 0014 0017 0014 0017 0014 0017 0014 0018 0015 0016 0014 0017 0014 0017 0014 0017 0015 0017 003F 0017 003F 0017 0014 0017 0041 0016 003F 0017 003F 0018 0040 0016 003F 0017 0014 0018 0014 0017 0015 0016 003F 0017 0014 0017 0040 0017 0015 0018 0012 0017 0040 0016 0041 0016 003F 0017 0014 0017 0040 0017 0015 0016 003F 0017 062E 0151 0056 0016 08FF</code>
    <code function='downArrow'>0000 006D 0024 0000 0152 00AC 0016 0015 0016 0014 0017 0014 0017 0014 0018 0014 0017 0015 0016 0014 0017 0014 0017 0015 0016 0040 0017 003F 0017 0014 0017 003F 0018 003F 0017 003F 0017 0041 0016 0014 0017 003F 0017 0040 0017 0015 0017 003E 0017 0015 0017 0040 0016 0015 0016 003F 0018 0013 0018 0014 0017 003F 0017 0014 0017 003F 0018 0015 0016 003F 0017 062D 0152 0056 0016 08FF</code>
    <code function='nextChapter'>0000 006D 0024 0000 0152 00AB 0017 0015 0016 0014 0017 0014 0017 0014 0018 0013 0018 0015 0017 0013 0017 0014 0017 0014 0018 003F 0017 003F 0018 0013 0017 0040 0017 003F 0017 003F 0018 003F 0017 003F 0017 0014 0017 0040 0017 003F 0017 003F 0017 0014 0018 003F 0017 0014 0017 0014 0017 0040 0017 0015 0016 0014 0017 0014 0017 003F 0018 0015 0016 003F 0017 062D 0152 0055 0017 08FF</code>
    <delay function='menuNavigation'>300</delay>
    <delay function='menuValidation'>2000</delay>
    <delay function='chapterNavigation'>1500</delay>
  </irProfile>
</irProfiles>